'use client'

import React, { useEffect, useState } from 'react'
import { Tag, Link2, FileText, AlertCircle } from 'lucide-react'

export const BLOG_CATEGORIES = [
  'Business Aviation',
  'FBO Services',
  'Industry News',
  'Company News',
  'Aviation Insights',
  'Services Update',
  'Case Studies',
  'Charter',
  'Maintenance',
  'General',
] as const

interface PostMetaProps {
  category: string
  onCategoryChange: (cat: string) => void
  slug: string
  onSlugChange: (slug: string) => void
  slugEdited: boolean
  onSlugEdit: () => void
  title: string
  excerpt: string
  onExcerptChange: (excerpt: string) => void
}

export function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim()
}

export function PostMeta({
  category,
  onCategoryChange,
  slug,
  onSlugChange,
  slugEdited,
  onSlugEdit,
  title,
  excerpt,
  onExcerptChange,
}: PostMetaProps) {
  const [slugError, setSlugError] = useState<string | null>(null)

  // Auto-generate slug when title changes unless user has manually edited it
  useEffect(() => {
    if (!slugEdited && title) {
      const autoGenerated = generateSlug(title)
      onSlugChange(autoGenerated)
    }
  }, [title, slugEdited, onSlugChange])

  const handleSlugInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value
    onSlugEdit() // Mark as manually edited

    // Validate slug: only lowercase letters, numbers, and hyphens
    const isValid = /^[a-z0-9-]*$/.test(val)
    if (!isValid) {
      setSlugError('Only lowercase letters, numbers, and hyphens allowed')
    } else {
      setSlugError(null)
    }

    onSlugChange(val)
  }

  return (
    <div className="bg-ean-black-accent/80 border border-ean-border-dark rounded-xl p-5 space-y-5 shadow-lg">
      <h3 className="text-sm font-semibold text-ean-white flex items-center gap-2 border-b border-ean-border-dark pb-3">
        <Tag className="w-4 h-4 text-ean-gold" />
        Post Settings
      </h3>

      {/* SECTION 1 — Category */}
      <div className="space-y-1.5">
        <label className="text-xs font-medium text-ean-muted-light flex items-center justify-between">
          <span>Category</span>
          <span className="text-[11px] text-ean-gold">Required</span>
        </label>
        <select
          value={category}
          onChange={(e) => onCategoryChange(e.target.value)}
          className="w-full px-3 py-2 bg-ean-black-pure border border-ean-border-dark rounded-lg text-xs text-ean-white focus:outline-none focus:border-ean-gold/60 cursor-pointer"
        >
          {BLOG_CATEGORIES.map((cat) => (
            <option key={cat} value={cat} className="bg-ean-black-pure text-ean-white">
              {cat}
            </option>
          ))}
        </select>
      </div>

      {/* SECTION 2 — Slug */}
      <div className="space-y-1.5">
        <label className="text-xs font-medium text-ean-muted-light flex items-center justify-between">
          <span className="flex items-center gap-1">
            <Link2 className="w-3.5 h-3.5 text-ean-gold" />
            URL Slug
          </span>
          {slugEdited && <span className="text-[10px] text-amber-400">Manual override</span>}
        </label>

        <input
          type="text"
          value={slug}
          onChange={handleSlugInputChange}
          placeholder="post-url-slug"
          className={`w-full px-3 py-2 bg-ean-black-pure border rounded-lg font-mono text-xs text-ean-white focus:outline-none transition-colors ${
            slugError
              ? 'border-red-500 focus:border-red-500 focus:ring-1 focus:ring-red-500/30'
              : 'border-ean-border-dark focus:border-ean-gold/60 focus:ring-1 focus:ring-ean-gold/30'
          }`}
        />

        {slugError ? (
          <p className="text-xs text-red-400 flex items-center gap-1 mt-1">
            <AlertCircle className="w-3 h-3 shrink-0" />
            {slugError}
          </p>
        ) : (
          <p className="text-[11px] text-ean-muted-light/60 font-mono truncate">
            ean.aero/blog/<span className="text-ean-gold">{slug || '[slug]'}</span>
          </p>
        )}
      </div>

      {/* SECTION 3 — Excerpt */}
      <div className="space-y-1.5">
        <label className="text-xs font-medium text-ean-muted-light flex items-center gap-1">
          <FileText className="w-3.5 h-3.5 text-ean-gold" />
          Post Excerpt
        </label>
        <textarea
          rows={3}
          value={excerpt}
          onChange={(e) => onExcerptChange(e.target.value)}
          placeholder="A short summary of this post (1-2 sentences)..."
          className="w-full px-3 py-2 bg-ean-black-pure border border-ean-border-dark rounded-lg text-xs text-ean-white focus:outline-none focus:border-ean-gold/60 focus:ring-1 focus:ring-ean-gold/30 resize-none leading-relaxed placeholder:text-ean-muted-light/40"
        />
        <div className="flex justify-end">
          <span className="text-[11px] font-mono text-ean-muted-light/60">
            {excerpt.length} characters
          </span>
        </div>
      </div>
    </div>
  )
}
