export interface FleetAircraft {
  id: string;
  name: string;
  manufacturer: string;
  category: 'Light Jet' | 'Midsize Jet' | 'Super Midsize' | 'Heavy Jet' | 'Ultra Long Range' | 'Helicopter' | 'VIP Airliner' | 'Turboprop';
  mtowKg: number;
  mtowRange: string;
  maxPassengers: number;
  icao: string;
  rangeNm: number;
  baseHandlingFeeUsd: {
    domestic: number;
    international: number;
  };
  landingParkingFeeUsdPerDay: {
    domestic: number;
    international: number;
  };
  paxFeeUsdPerPax: number;
  popular?: boolean;
}

export interface QuoteCalculationInput {
  aircraftId: string;
  customAircraft?: FleetAircraft;
  location: 'lagos' | 'abuja';
  operation: 'domestic' | 'international';
  movement: 'weekday' | 'weekend';
  passengers: number;
  stay: 'same_day' | 'overnight';
  overnightNights?: number;
  addOns?: {
    vipLounge?: boolean;
    catering?: boolean;
    gpuPower?: boolean;
    waterService?: boolean;
  };
}

export interface QuoteItemBreakdown {
  label: string;
  amountUsd: number;
  detail?: string;
}

export interface QuoteCalculationResult {
  aircraft: FleetAircraft;
  locationName: string;
  operationName: string;
  movementName: string;
  stayName: string;
  passengers: number;
  breakdown: QuoteItemBreakdown[];
  totalUsd: number;
  totalNgn: number;
  fxRate: number;
}

export const AIRCRAFT_DATASET: FleetAircraft[] = [
  // ==================== ULTRA LONG RANGE JETS ====================
  {
    id: 'gulfstream-g700',
    name: 'Gulfstream G700',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Ultra Long Range',
    mtowKg: 48761,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 19,
    icao: 'GLF7',
    rangeNm: 7500,
    baseHandlingFeeUsd: { domestic: 2500, international: 3900 },
    landingParkingFeeUsdPerDay: { domestic: 500, international: 980 },
    paxFeeUsdPerPax: 55,
    popular: true,
  },
  {
    id: 'gulfstream-g650er',
    name: 'Gulfstream G650ER',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Ultra Long Range',
    mtowKg: 45360,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 19,
    icao: 'GLF6',
    rangeNm: 7500,
    baseHandlingFeeUsd: { domestic: 2400, international: 3800 },
    landingParkingFeeUsdPerDay: { domestic: 480, international: 950 },
    paxFeeUsdPerPax: 50,
    popular: true,
  },
  {
    id: 'gulfstream-g650',
    name: 'Gulfstream G650',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Ultra Long Range',
    mtowKg: 45178,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 18,
    icao: 'GLF6',
    rangeNm: 7000,
    baseHandlingFeeUsd: { domestic: 2350, international: 3750 },
    landingParkingFeeUsdPerDay: { domestic: 475, international: 940 },
    paxFeeUsdPerPax: 50,
  },
  {
    id: 'gulfstream-g600',
    name: 'Gulfstream G600',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Ultra Long Range',
    mtowKg: 42864,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 19,
    icao: 'G600',
    rangeNm: 6600,
    baseHandlingFeeUsd: { domestic: 2250, international: 3600 },
    landingParkingFeeUsdPerDay: { domestic: 460, international: 910 },
    paxFeeUsdPerPax: 50,
  },
  {
    id: 'gulfstream-g550',
    name: 'Gulfstream G550',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Ultra Long Range',
    mtowKg: 41277,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 16,
    icao: 'GLF5',
    rangeNm: 6750,
    baseHandlingFeeUsd: { domestic: 2200, international: 3500 },
    landingParkingFeeUsdPerDay: { domestic: 450, international: 900 },
    paxFeeUsdPerPax: 50,
    popular: true,
  },
  {
    id: 'gulfstream-g500',
    name: 'Gulfstream G500',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Ultra Long Range',
    mtowKg: 36106,
    mtowRange: '30,001 – 40,000 kg',
    maxPassengers: 19,
    icao: 'G500',
    rangeNm: 5300,
    baseHandlingFeeUsd: { domestic: 2150, international: 3400 },
    landingParkingFeeUsdPerDay: { domestic: 430, international: 850 },
    paxFeeUsdPerPax: 50,
  },
  {
    id: 'gulfstream-gv',
    name: 'Gulfstream GV',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Ultra Long Range',
    mtowKg: 41050,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 16,
    icao: 'GLF5',
    rangeNm: 6500,
    baseHandlingFeeUsd: { domestic: 2200, international: 3500 },
    landingParkingFeeUsdPerDay: { domestic: 450, international: 900 },
    paxFeeUsdPerPax: 50,
  },
  {
    id: 'bombardier-global-7500',
    name: 'Bombardier Global 7500',
    manufacturer: 'Bombardier',
    category: 'Ultra Long Range',
    mtowKg: 52163,
    mtowRange: '50,001 – 60,000 kg',
    maxPassengers: 19,
    icao: 'GL7T',
    rangeNm: 7700,
    baseHandlingFeeUsd: { domestic: 2700, international: 4200 },
    landingParkingFeeUsdPerDay: { domestic: 550, international: 1100 },
    paxFeeUsdPerPax: 55,
    popular: true,
  },
  {
    id: 'bombardier-global-6500',
    name: 'Bombardier Global 6500',
    manufacturer: 'Bombardier',
    category: 'Ultra Long Range',
    mtowKg: 45042,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 17,
    icao: 'GLEX',
    rangeNm: 6600,
    baseHandlingFeeUsd: { domestic: 2350, international: 3650 },
    landingParkingFeeUsdPerDay: { domestic: 475, international: 930 },
    paxFeeUsdPerPax: 50,
  },
  {
    id: 'bombardier-global-6000',
    name: 'Bombardier Global 6000',
    manufacturer: 'Bombardier',
    category: 'Ultra Long Range',
    mtowKg: 45132,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 17,
    icao: 'GLEX',
    rangeNm: 6000,
    baseHandlingFeeUsd: { domestic: 2300, international: 3600 },
    landingParkingFeeUsdPerDay: { domestic: 470, international: 920 },
    paxFeeUsdPerPax: 50,
    popular: true,
  },
  {
    id: 'bombardier-global-5500',
    name: 'Bombardier Global 5500',
    manufacturer: 'Bombardier',
    category: 'Ultra Long Range',
    mtowKg: 41957,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 16,
    icao: 'GLEX',
    rangeNm: 5900,
    baseHandlingFeeUsd: { domestic: 2250, international: 3550 },
    landingParkingFeeUsdPerDay: { domestic: 455, international: 900 },
    paxFeeUsdPerPax: 50,
  },
  {
    id: 'bombardier-global-5000',
    name: 'Bombardier Global 5000',
    manufacturer: 'Bombardier',
    category: 'Ultra Long Range',
    mtowKg: 41957,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 16,
    icao: 'GL5T',
    rangeNm: 5200,
    baseHandlingFeeUsd: { domestic: 2200, international: 3500 },
    landingParkingFeeUsdPerDay: { domestic: 450, international: 890 },
    paxFeeUsdPerPax: 50,
  },
  {
    id: 'bombardier-global-express-xrs',
    name: 'Bombardier Global Express XRS',
    manufacturer: 'Bombardier',
    category: 'Ultra Long Range',
    mtowKg: 45132,
    mtowRange: '40,001 – 50,000 kg',
    maxPassengers: 16,
    icao: 'GLEX',
    rangeNm: 6150,
    baseHandlingFeeUsd: { domestic: 2300, international: 3600 },
    landingParkingFeeUsdPerDay: { domestic: 470, international: 920 },
    paxFeeUsdPerPax: 50,
  },
  {
    id: 'dassault-falcon-10x',
    name: 'Dassault Falcon 10X',
    manufacturer: 'Dassault Aviation',
    category: 'Ultra Long Range',
    mtowKg: 52163,
    mtowRange: '50,001 – 60,000 kg',
    maxPassengers: 19,
    icao: 'F10X',
    rangeNm: 7500,
    baseHandlingFeeUsd: { domestic: 2650, international: 4100 },
    landingParkingFeeUsdPerDay: { domestic: 540, international: 1050 },
    paxFeeUsdPerPax: 55,
  },
  {
    id: 'dassault-falcon-8x',
    name: 'Dassault Falcon 8X',
    manufacturer: 'Dassault Aviation',
    category: 'Ultra Long Range',
    mtowKg: 33112,
    mtowRange: '30,001 – 40,000 kg',
    maxPassengers: 16,
    icao: 'FA8X',
    rangeNm: 6450,
    baseHandlingFeeUsd: { domestic: 2150, international: 3350 },
    landingParkingFeeUsdPerDay: { domestic: 430, international: 840 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'falcon-7x',
    name: 'Dassault Falcon 7X',
    manufacturer: 'Dassault Aviation',
    category: 'Ultra Long Range',
    mtowKg: 31751,
    mtowRange: '30,001 – 40,000 kg',
    maxPassengers: 14,
    icao: 'FA7X',
    rangeNm: 5950,
    baseHandlingFeeUsd: { domestic: 2100, international: 3300 },
    landingParkingFeeUsdPerDay: { domestic: 420, international: 820 },
    paxFeeUsdPerPax: 45,
    popular: true,
  },

  // ==================== HEAVY JETS ====================
  {
    id: 'embraer-legacy-650',
    name: 'Embraer Legacy 650',
    manufacturer: 'Embraer',
    category: 'Heavy Jet',
    mtowKg: 24300,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 14,
    icao: 'E35L',
    rangeNm: 3900,
    baseHandlingFeeUsd: { domestic: 1850, international: 2950 },
    landingParkingFeeUsdPerDay: { domestic: 320, international: 650 },
    paxFeeUsdPerPax: 45,
    popular: true,
  },
  {
    id: 'embraer-legacy-650e',
    name: 'Embraer Legacy 650E',
    manufacturer: 'Embraer',
    category: 'Heavy Jet',
    mtowKg: 24300,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 14,
    icao: 'E35L',
    rangeNm: 3900,
    baseHandlingFeeUsd: { domestic: 1850, international: 2950 },
    landingParkingFeeUsdPerDay: { domestic: 320, international: 650 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'embraer-legacy-600',
    name: 'Embraer Legacy 600',
    manufacturer: 'Embraer',
    category: 'Heavy Jet',
    mtowKg: 22500,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 13,
    icao: 'E135',
    rangeNm: 3250,
    baseHandlingFeeUsd: { domestic: 1800, international: 2850 },
    landingParkingFeeUsdPerDay: { domestic: 310, international: 630 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'challenger-650',
    name: 'Bombardier Challenger 650',
    manufacturer: 'Bombardier',
    category: 'Heavy Jet',
    mtowKg: 21863,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 12,
    icao: 'CL60',
    rangeNm: 4000,
    baseHandlingFeeUsd: { domestic: 1800, international: 2850 },
    landingParkingFeeUsdPerDay: { domestic: 310, international: 620 },
    paxFeeUsdPerPax: 45,
    popular: true,
  },
  {
    id: 'challenger-605',
    name: 'Bombardier Challenger 605',
    manufacturer: 'Bombardier',
    category: 'Heavy Jet',
    mtowKg: 21863,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 12,
    icao: 'CL60',
    rangeNm: 4000,
    baseHandlingFeeUsd: { domestic: 1800, international: 2850 },
    landingParkingFeeUsdPerDay: { domestic: 310, international: 620 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'challenger-604',
    name: 'Bombardier Challenger 604',
    manufacturer: 'Bombardier',
    category: 'Heavy Jet',
    mtowKg: 21863,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 12,
    icao: 'CL60',
    rangeNm: 3850,
    baseHandlingFeeUsd: { domestic: 1780, international: 2800 },
    landingParkingFeeUsdPerDay: { domestic: 300, international: 610 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'dassault-falcon-900lx',
    name: 'Dassault Falcon 900LX',
    manufacturer: 'Dassault Aviation',
    category: 'Heavy Jet',
    mtowKg: 21908,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 14,
    icao: 'F900',
    rangeNm: 4750,
    baseHandlingFeeUsd: { domestic: 1820, international: 2880 },
    landingParkingFeeUsdPerDay: { domestic: 315, international: 625 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'dassault-falcon-900ex',
    name: 'Dassault Falcon 900EX',
    manufacturer: 'Dassault Aviation',
    category: 'Heavy Jet',
    mtowKg: 21908,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 14,
    icao: 'F900',
    rangeNm: 4500,
    baseHandlingFeeUsd: { domestic: 1800, international: 2850 },
    landingParkingFeeUsdPerDay: { domestic: 310, international: 620 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'falcon-2000ex',
    name: 'Dassault Falcon 2000EX',
    manufacturer: 'Dassault Aviation',
    category: 'Heavy Jet',
    mtowKg: 19142,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 10,
    icao: 'F2TH',
    rangeNm: 3800,
    baseHandlingFeeUsd: { domestic: 1600, international: 2500 },
    landingParkingFeeUsdPerDay: { domestic: 270, international: 530 },
    paxFeeUsdPerPax: 40,
    popular: true,
  },
  {
    id: 'dassault-falcon-2000lxs',
    name: 'Dassault Falcon 2000LXS',
    manufacturer: 'Dassault Aviation',
    category: 'Heavy Jet',
    mtowKg: 19414,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 10,
    icao: 'F2TH',
    rangeNm: 4000,
    baseHandlingFeeUsd: { domestic: 1620, international: 2550 },
    landingParkingFeeUsdPerDay: { domestic: 275, international: 540 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'gulfstream-g450',
    name: 'Gulfstream G450',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Heavy Jet',
    mtowKg: 33521,
    mtowRange: '30,001 – 40,000 kg',
    maxPassengers: 14,
    icao: 'G450',
    rangeNm: 4350,
    baseHandlingFeeUsd: { domestic: 2000, international: 3150 },
    landingParkingFeeUsdPerDay: { domestic: 390, international: 780 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'gulfstream-giv-sp',
    name: 'Gulfstream GIV-SP',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Heavy Jet',
    mtowKg: 33838,
    mtowRange: '30,001 – 40,000 kg',
    maxPassengers: 14,
    icao: 'GIV',
    rangeNm: 4220,
    baseHandlingFeeUsd: { domestic: 1980, international: 3100 },
    landingParkingFeeUsdPerDay: { domestic: 385, international: 770 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'gulfstream-giv',
    name: 'Gulfstream GIV',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Heavy Jet',
    mtowKg: 33203,
    mtowRange: '30,001 – 40,000 kg',
    maxPassengers: 14,
    icao: 'GIV',
    rangeNm: 4100,
    baseHandlingFeeUsd: { domestic: 1950, international: 3050 },
    landingParkingFeeUsdPerDay: { domestic: 380, international: 760 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'hawker-4000',
    name: 'Hawker 4000',
    manufacturer: 'Hawker Beechcraft',
    category: 'Heavy Jet',
    mtowKg: 17917,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 10,
    icao: 'HA4C',
    rangeNm: 3280,
    baseHandlingFeeUsd: { domestic: 1550, international: 2400 },
    landingParkingFeeUsdPerDay: { domestic: 260, international: 510 },
    paxFeeUsdPerPax: 40,
  },

  // ==================== SUPER MIDSIZE JETS ====================
  {
    id: 'challenger-350',
    name: 'Bombardier Challenger 350',
    manufacturer: 'Bombardier',
    category: 'Super Midsize',
    mtowKg: 18416,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 10,
    icao: 'CL35',
    rangeNm: 3200,
    baseHandlingFeeUsd: { domestic: 1550, international: 2400 },
    landingParkingFeeUsdPerDay: { domestic: 260, international: 510 },
    paxFeeUsdPerPax: 40,
    popular: true,
  },
  {
    id: 'challenger-3500',
    name: 'Bombardier Challenger 3500',
    manufacturer: 'Bombardier',
    category: 'Super Midsize',
    mtowKg: 18416,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 10,
    icao: 'CL35',
    rangeNm: 3400,
    baseHandlingFeeUsd: { domestic: 1580, international: 2450 },
    landingParkingFeeUsdPerDay: { domestic: 265, international: 520 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'challenger-300',
    name: 'Bombardier Challenger 300',
    manufacturer: 'Bombardier',
    category: 'Super Midsize',
    mtowKg: 17622,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 9,
    icao: 'CL30',
    rangeNm: 3100,
    baseHandlingFeeUsd: { domestic: 1500, international: 2350 },
    landingParkingFeeUsdPerDay: { domestic: 250, international: 500 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'embraer-praetor-600',
    name: 'Embraer Praetor 600',
    manufacturer: 'Embraer',
    category: 'Super Midsize',
    mtowKg: 21380,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 12,
    icao: 'E55P',
    rangeNm: 4018,
    baseHandlingFeeUsd: { domestic: 1750, international: 2700 },
    landingParkingFeeUsdPerDay: { domestic: 300, international: 600 },
    paxFeeUsdPerPax: 40,
    popular: true,
  },
  {
    id: 'embraer-praetor-500',
    name: 'Embraer Praetor 500',
    manufacturer: 'Embraer',
    category: 'Super Midsize',
    mtowKg: 17040,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 9,
    icao: 'E545',
    rangeNm: 3340,
    baseHandlingFeeUsd: { domestic: 1500, international: 2350 },
    landingParkingFeeUsdPerDay: { domestic: 250, international: 500 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'embraer-legacy-500',
    name: 'Embraer Legacy 500',
    manufacturer: 'Embraer',
    category: 'Super Midsize',
    mtowKg: 17440,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 12,
    icao: 'E550',
    rangeNm: 3125,
    baseHandlingFeeUsd: { domestic: 1520, international: 2380 },
    landingParkingFeeUsdPerDay: { domestic: 255, international: 505 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'embraer-legacy-450',
    name: 'Embraer Legacy 450',
    manufacturer: 'Embraer',
    category: 'Super Midsize',
    mtowKg: 16000,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 9,
    icao: 'E545',
    rangeNm: 2900,
    baseHandlingFeeUsd: { domestic: 1480, international: 2300 },
    landingParkingFeeUsdPerDay: { domestic: 245, international: 490 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'gulfstream-g280',
    name: 'Gulfstream G280',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Super Midsize',
    mtowKg: 17962,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 10,
    icao: 'G280',
    rangeNm: 3600,
    baseHandlingFeeUsd: { domestic: 1550, international: 2400 },
    landingParkingFeeUsdPerDay: { domestic: 260, international: 510 },
    paxFeeUsdPerPax: 40,
    popular: true,
  },
  {
    id: 'gulfstream-g200',
    name: 'Gulfstream G200',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Super Midsize',
    mtowKg: 16080,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 9,
    icao: 'G200',
    rangeNm: 3400,
    baseHandlingFeeUsd: { domestic: 1480, international: 2300 },
    landingParkingFeeUsdPerDay: { domestic: 245, international: 490 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'citation-longitude',
    name: 'Cessna Citation Longitude',
    manufacturer: 'Textron Aviation',
    category: 'Super Midsize',
    mtowKg: 17917,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 12,
    icao: 'C700',
    rangeNm: 3500,
    baseHandlingFeeUsd: { domestic: 1550, international: 2400 },
    landingParkingFeeUsdPerDay: { domestic: 260, international: 510 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'citation-sovereign-plus',
    name: 'Cessna Citation Sovereign+',
    manufacturer: 'Textron Aviation',
    category: 'Super Midsize',
    mtowKg: 13744,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 9,
    icao: 'C680',
    rangeNm: 3200,
    baseHandlingFeeUsd: { domestic: 1380, international: 2150 },
    landingParkingFeeUsdPerDay: { domestic: 225, international: 450 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'citation-x-plus',
    name: 'Cessna Citation X+',
    manufacturer: 'Textron Aviation',
    category: 'Super Midsize',
    mtowKg: 16601,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 12,
    icao: 'C750',
    rangeNm: 3460,
    baseHandlingFeeUsd: { domestic: 1500, international: 2350 },
    landingParkingFeeUsdPerDay: { domestic: 250, international: 500 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'falcon-50ex',
    name: 'Dassault Falcon 50EX',
    manufacturer: 'Dassault Aviation',
    category: 'Super Midsize',
    mtowKg: 18008,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 9,
    icao: 'FA50',
    rangeNm: 3200,
    baseHandlingFeeUsd: { domestic: 1550, international: 2400 },
    landingParkingFeeUsdPerDay: { domestic: 260, international: 510 },
    paxFeeUsdPerPax: 40,
  },

  // ==================== MIDSIZE JETS ====================
  {
    id: 'hawker-800xp',
    name: 'Hawker 800XP / 900XP',
    manufacturer: 'Hawker Beechcraft',
    category: 'Midsize Jet',
    mtowKg: 12700,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 8,
    icao: 'H25B',
    rangeNm: 2700,
    baseHandlingFeeUsd: { domestic: 1300, international: 2050 },
    landingParkingFeeUsdPerDay: { domestic: 210, international: 420 },
    paxFeeUsdPerPax: 35,
    popular: true,
  },
  {
    id: 'hawker-900xp',
    name: 'Hawker 900XP',
    manufacturer: 'Hawker Beechcraft',
    category: 'Midsize Jet',
    mtowKg: 12700,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 8,
    icao: 'H25B',
    rangeNm: 2800,
    baseHandlingFeeUsd: { domestic: 1300, international: 2050 },
    landingParkingFeeUsdPerDay: { domestic: 210, international: 420 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'hawker-850xp',
    name: 'Hawker 850XP',
    manufacturer: 'Hawker Beechcraft',
    category: 'Midsize Jet',
    mtowKg: 12700,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 8,
    icao: 'H25B',
    rangeNm: 2642,
    baseHandlingFeeUsd: { domestic: 1300, international: 2050 },
    landingParkingFeeUsdPerDay: { domestic: 210, international: 420 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'hawker-750',
    name: 'Hawker 750',
    manufacturer: 'Hawker Beechcraft',
    category: 'Midsize Jet',
    mtowKg: 12700,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 8,
    icao: 'H25B',
    rangeNm: 2100,
    baseHandlingFeeUsd: { domestic: 1280, international: 2000 },
    landingParkingFeeUsdPerDay: { domestic: 205, international: 410 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'citation-latitude',
    name: 'Cessna Citation Latitude',
    manufacturer: 'Textron Aviation',
    category: 'Midsize Jet',
    mtowKg: 14016,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 9,
    icao: 'C68A',
    rangeNm: 2700,
    baseHandlingFeeUsd: { domestic: 1350, international: 2100 },
    landingParkingFeeUsdPerDay: { domestic: 220, international: 440 },
    paxFeeUsdPerPax: 35,
    popular: true,
  },
  {
    id: 'citation-xls',
    name: 'Cessna Citation XLS+',
    manufacturer: 'Textron Aviation',
    category: 'Midsize Jet',
    mtowKg: 9163,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 9,
    icao: 'C56X',
    rangeNm: 2100,
    baseHandlingFeeUsd: { domestic: 1150, international: 1800 },
    landingParkingFeeUsdPerDay: { domestic: 180, international: 360 },
    paxFeeUsdPerPax: 35,
    popular: true,
  },
  {
    id: 'citation-excel',
    name: 'Cessna Citation Excel',
    manufacturer: 'Textron Aviation',
    category: 'Midsize Jet',
    mtowKg: 9072,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 8,
    icao: 'C56X',
    rangeNm: 1900,
    baseHandlingFeeUsd: { domestic: 1120, international: 1780 },
    landingParkingFeeUsdPerDay: { domestic: 175, international: 350 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'learjet-75',
    name: 'Learjet 75',
    manufacturer: 'Bombardier',
    category: 'Midsize Jet',
    mtowKg: 9752,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 9,
    icao: 'LJ75',
    rangeNm: 2040,
    baseHandlingFeeUsd: { domestic: 1180, international: 1850 },
    landingParkingFeeUsdPerDay: { domestic: 185, international: 370 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'learjet-60xr',
    name: 'Learjet 60XR',
    manufacturer: 'Bombardier',
    category: 'Midsize Jet',
    mtowKg: 10659,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 8,
    icao: 'LJ60',
    rangeNm: 2405,
    baseHandlingFeeUsd: { domestic: 1220, international: 1900 },
    landingParkingFeeUsdPerDay: { domestic: 195, international: 390 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'gulfstream-g150',
    name: 'Gulfstream G150',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Midsize Jet',
    mtowKg: 11839,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 8,
    icao: 'G150',
    rangeNm: 3000,
    baseHandlingFeeUsd: { domestic: 1250, international: 1950 },
    landingParkingFeeUsdPerDay: { domestic: 200, international: 400 },
    paxFeeUsdPerPax: 35,
  },

  // ==================== LIGHT JETS & VERY LIGHT JETS ====================
  {
    id: 'phenom-300e',
    name: 'Embraer Phenom 300E',
    manufacturer: 'Embraer',
    category: 'Light Jet',
    mtowKg: 8150,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 8,
    icao: 'E55P',
    rangeNm: 2010,
    baseHandlingFeeUsd: { domestic: 1100, international: 1750 },
    landingParkingFeeUsdPerDay: { domestic: 170, international: 340 },
    paxFeeUsdPerPax: 30,
    popular: true,
  },
  {
    id: 'phenom-100ev',
    name: 'Embraer Phenom 100EV',
    manufacturer: 'Embraer',
    category: 'Light Jet',
    mtowKg: 4800,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 6,
    icao: 'E50P',
    rangeNm: 1178,
    baseHandlingFeeUsd: { domestic: 950, international: 1450 },
    landingParkingFeeUsdPerDay: { domestic: 140, international: 280 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'citation-cj4',
    name: 'Cessna Citation CJ4',
    manufacturer: 'Textron Aviation',
    category: 'Light Jet',
    mtowKg: 7761,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 9,
    icao: 'C25C',
    rangeNm: 2165,
    baseHandlingFeeUsd: { domestic: 1080, international: 1700 },
    landingParkingFeeUsdPerDay: { domestic: 165, international: 330 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'citation-cj3-plus',
    name: 'Cessna Citation CJ3+',
    manufacturer: 'Textron Aviation',
    category: 'Light Jet',
    mtowKg: 6260,
    mtowRange: '5,001 – 7,000 kg',
    maxPassengers: 7,
    icao: 'C25B',
    rangeNm: 2040,
    baseHandlingFeeUsd: { domestic: 1020, international: 1600 },
    landingParkingFeeUsdPerDay: { domestic: 150, international: 300 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'citation-cj2-plus',
    name: 'Cessna Citation CJ2+',
    manufacturer: 'Textron Aviation',
    category: 'Light Jet',
    mtowKg: 5670,
    mtowRange: '5,001 – 7,000 kg',
    maxPassengers: 6,
    icao: 'C25A',
    rangeNm: 1780,
    baseHandlingFeeUsd: { domestic: 990, international: 1550 },
    landingParkingFeeUsdPerDay: { domestic: 145, international: 290 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'citation-m2',
    name: 'Cessna Citation M2',
    manufacturer: 'Textron Aviation',
    category: 'Light Jet',
    mtowKg: 4853,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 6,
    icao: 'C25M',
    rangeNm: 1550,
    baseHandlingFeeUsd: { domestic: 950, international: 1450 },
    landingParkingFeeUsdPerDay: { domestic: 140, international: 280 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'citation-mustang',
    name: 'Cessna Citation Mustang',
    manufacturer: 'Textron Aviation',
    category: 'Light Jet',
    mtowKg: 3923,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 4,
    icao: 'C510',
    rangeNm: 1200,
    baseHandlingFeeUsd: { domestic: 900, international: 1400 },
    landingParkingFeeUsdPerDay: { domestic: 130, international: 260 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'hondajet-elite-ii',
    name: 'HondaJet Elite II',
    manufacturer: 'Honda Aircraft Company',
    category: 'Light Jet',
    mtowKg: 4944,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 6,
    icao: 'HA420',
    rangeNm: 1547,
    baseHandlingFeeUsd: { domestic: 960, international: 1480 },
    landingParkingFeeUsdPerDay: { domestic: 142, international: 284 },
    paxFeeUsdPerPax: 30,
    popular: true,
  },
  {
    id: 'nextant-400xti',
    name: 'Nextant 400XTi',
    manufacturer: 'Nextant Aerospace',
    category: 'Light Jet',
    mtowKg: 7394,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 7,
    icao: 'BE40',
    rangeNm: 2005,
    baseHandlingFeeUsd: { domestic: 1050, international: 1650 },
    landingParkingFeeUsdPerDay: { domestic: 160, international: 320 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'hawker-400xp',
    name: 'Hawker 400XP / Beechjet 400A',
    manufacturer: 'Hawker Beechcraft',
    category: 'Light Jet',
    mtowKg: 7394,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 7,
    icao: 'BE40',
    rangeNm: 1400,
    baseHandlingFeeUsd: { domestic: 1050, international: 1650 },
    landingParkingFeeUsdPerDay: { domestic: 160, international: 320 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'eclipse-550',
    name: 'Eclipse 550',
    manufacturer: 'One Aviation / Eclipse',
    category: 'Light Jet',
    mtowKg: 2722,
    mtowRange: '0 – 3,000 kg',
    maxPassengers: 5,
    icao: 'EA50',
    rangeNm: 1125,
    baseHandlingFeeUsd: { domestic: 850, international: 1300 },
    landingParkingFeeUsdPerDay: { domestic: 120, international: 240 },
    paxFeeUsdPerPax: 25,
  },

  // ==================== TURBOPROPS ====================
  {
    id: 'king-air-350',
    name: 'Beechcraft King Air 350i',
    manufacturer: 'Textron Aviation',
    category: 'Turboprop',
    mtowKg: 6804,
    mtowRange: '5,001 – 7,000 kg',
    maxPassengers: 9,
    icao: 'B350',
    rangeNm: 1800,
    baseHandlingFeeUsd: { domestic: 950, international: 1450 },
    landingParkingFeeUsdPerDay: { domestic: 140, international: 280 },
    paxFeeUsdPerPax: 25,
    popular: true,
  },
  {
    id: 'king-air-360',
    name: 'Beechcraft King Air 360',
    manufacturer: 'Textron Aviation',
    category: 'Turboprop',
    mtowKg: 6804,
    mtowRange: '5,001 – 7,000 kg',
    maxPassengers: 9,
    icao: 'B350',
    rangeNm: 1806,
    baseHandlingFeeUsd: { domestic: 950, international: 1450 },
    landingParkingFeeUsdPerDay: { domestic: 140, international: 280 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'king-air-250',
    name: 'Beechcraft King Air 250 / 200',
    manufacturer: 'Textron Aviation',
    category: 'Turboprop',
    mtowKg: 5670,
    mtowRange: '5,001 – 7,000 kg',
    maxPassengers: 8,
    icao: 'BE20',
    rangeNm: 1580,
    baseHandlingFeeUsd: { domestic: 900, international: 1380 },
    landingParkingFeeUsdPerDay: { domestic: 130, international: 260 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'pilatus-pc12-ngx',
    name: 'Pilatus PC-12 NGX',
    manufacturer: 'Pilatus Aircraft',
    category: 'Turboprop',
    mtowKg: 4740,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 9,
    icao: 'PC12',
    rangeNm: 1803,
    baseHandlingFeeUsd: { domestic: 880, international: 1350 },
    landingParkingFeeUsdPerDay: { domestic: 125, international: 250 },
    paxFeeUsdPerPax: 25,
    popular: true,
  },
  {
    id: 'pilatus-pc24',
    name: 'Pilatus PC-24 Super Versatile Jet',
    manufacturer: 'Pilatus Aircraft',
    category: 'Light Jet',
    mtowKg: 8300,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 11,
    icao: 'PC24',
    rangeNm: 2000,
    baseHandlingFeeUsd: { domestic: 1100, international: 1750 },
    landingParkingFeeUsdPerDay: { domestic: 170, international: 340 },
    paxFeeUsdPerPax: 30,
    popular: true,
  },
  {
    id: 'piaggio-avanti-evo',
    name: 'Piaggio P.180 Avanti EVO',
    manufacturer: 'Piaggio Aerospace',
    category: 'Turboprop',
    mtowKg: 5489,
    mtowRange: '5,001 – 7,000 kg',
    maxPassengers: 8,
    icao: 'P180',
    rangeNm: 1800,
    baseHandlingFeeUsd: { domestic: 920, international: 1400 },
    landingParkingFeeUsdPerDay: { domestic: 135, international: 270 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'tbm-960',
    name: 'Daher TBM 960',
    manufacturer: 'Daher',
    category: 'Turboprop',
    mtowKg: 3354,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 5,
    icao: 'TBM9',
    rangeNm: 1730,
    baseHandlingFeeUsd: { domestic: 820, international: 1250 },
    landingParkingFeeUsdPerDay: { domestic: 115, international: 230 },
    paxFeeUsdPerPax: 25,
  },

  // ==================== HELICOPTERS ====================
  {
    id: 'airbus-h175',
    name: 'Airbus H175 Helicopter',
    manufacturer: 'Airbus Helicopters',
    category: 'Helicopter',
    mtowKg: 7800,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 16,
    icao: 'EC75',
    rangeNm: 600,
    baseHandlingFeeUsd: { domestic: 1050, international: 1600 },
    landingParkingFeeUsdPerDay: { domestic: 160, international: 320 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'airbus-h160',
    name: 'Airbus H160 Helicopter',
    manufacturer: 'Airbus Helicopters',
    category: 'Helicopter',
    mtowKg: 6050,
    mtowRange: '5,001 – 7,000 kg',
    maxPassengers: 12,
    icao: 'H160',
    rangeNm: 475,
    baseHandlingFeeUsd: { domestic: 950, international: 1450 },
    landingParkingFeeUsdPerDay: { domestic: 140, international: 280 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'airbus-h145',
    name: 'Airbus H145 Helicopter',
    manufacturer: 'Airbus Helicopters',
    category: 'Helicopter',
    mtowKg: 3700,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 8,
    icao: 'EC45',
    rangeNm: 350,
    baseHandlingFeeUsd: { domestic: 750, international: 1200 },
    landingParkingFeeUsdPerDay: { domestic: 110, international: 220 },
    paxFeeUsdPerPax: 25,
    popular: true,
  },
  {
    id: 'airbus-h125',
    name: 'Airbus H125 (Écureuil)',
    manufacturer: 'Airbus Helicopters',
    category: 'Helicopter',
    mtowKg: 2250,
    mtowRange: '0 – 3,000 kg',
    maxPassengers: 5,
    icao: 'AS50',
    rangeNm: 340,
    baseHandlingFeeUsd: { domestic: 600, international: 980 },
    landingParkingFeeUsdPerDay: { domestic: 90, international: 180 },
    paxFeeUsdPerPax: 20,
    popular: true,
  },
  {
    id: 'bell-429',
    name: 'Bell 429 GlobalRanger',
    manufacturer: 'Bell Helicopter',
    category: 'Helicopter',
    mtowKg: 3175,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 7,
    icao: 'B429',
    rangeNm: 411,
    baseHandlingFeeUsd: { domestic: 720, international: 1150 },
    landingParkingFeeUsdPerDay: { domestic: 105, international: 210 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'bell-407gxi',
    name: 'Bell 407GXi',
    manufacturer: 'Bell Helicopter',
    category: 'Helicopter',
    mtowKg: 2381,
    mtowRange: '0 – 3,000 kg',
    maxPassengers: 6,
    icao: 'B407',
    rangeNm: 337,
    baseHandlingFeeUsd: { domestic: 620, international: 1000 },
    landingParkingFeeUsdPerDay: { domestic: 95, international: 190 },
    paxFeeUsdPerPax: 20,
  },
  {
    id: 'sikorsky-s92-vip',
    name: 'Sikorsky S-92 VIP',
    manufacturer: 'Sikorsky Aircraft',
    category: 'Helicopter',
    mtowKg: 12565,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 19,
    icao: 'S92',
    rangeNm: 540,
    baseHandlingFeeUsd: { domestic: 1300, international: 2050 },
    landingParkingFeeUsdPerDay: { domestic: 210, international: 420 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'sikorsky-s76d',
    name: 'Sikorsky S-76D VIP',
    manufacturer: 'Sikorsky Aircraft',
    category: 'Helicopter',
    mtowKg: 5307,
    mtowRange: '5,001 – 7,000 kg',
    maxPassengers: 8,
    icao: 'S76',
    rangeNm: 440,
    baseHandlingFeeUsd: { domestic: 880, international: 1380 },
    landingParkingFeeUsdPerDay: { domestic: 130, international: 260 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'leonardo-aw139',
    name: 'Leonardo AW139',
    manufacturer: 'Leonardo Helicopters',
    category: 'Helicopter',
    mtowKg: 7000,
    mtowRange: '5,001 – 7,000 kg',
    maxPassengers: 15,
    icao: 'A139',
    rangeNm: 573,
    baseHandlingFeeUsd: { domestic: 980, international: 1500 },
    landingParkingFeeUsdPerDay: { domestic: 145, international: 290 },
    paxFeeUsdPerPax: 30,
    popular: true,
  },
  {
    id: 'leonardo-aw109',
    name: 'Leonardo AW109 GrandNew',
    manufacturer: 'Leonardo Helicopters',
    category: 'Helicopter',
    mtowKg: 3175,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 6,
    icao: 'A109',
    rangeNm: 450,
    baseHandlingFeeUsd: { domestic: 700, international: 1120 },
    landingParkingFeeUsdPerDay: { domestic: 100, international: 200 },
    paxFeeUsdPerPax: 25,
  },

  // ==================== VIP AIRLINERS ====================
  {
    id: 'boeing-bbj',
    name: 'Boeing BBJ 737 VIP',
    manufacturer: 'Boeing Corporate Jets',
    category: 'VIP Airliner',
    mtowKg: 77564,
    mtowRange: '70,000+ kg',
    maxPassengers: 30,
    icao: 'B737',
    rangeNm: 6200,
    baseHandlingFeeUsd: { domestic: 3800, international: 5900 },
    landingParkingFeeUsdPerDay: { domestic: 850, international: 1650 },
    paxFeeUsdPerPax: 65,
    popular: true,
  },
  {
    id: 'boeing-bbj-max8',
    name: 'Boeing BBJ MAX 8',
    manufacturer: 'Boeing Corporate Jets',
    category: 'VIP Airliner',
    mtowKg: 82191,
    mtowRange: '70,000+ kg',
    maxPassengers: 30,
    icao: 'B738',
    rangeNm: 6640,
    baseHandlingFeeUsd: { domestic: 3950, international: 6100 },
    landingParkingFeeUsdPerDay: { domestic: 900, international: 1750 },
    paxFeeUsdPerPax: 65,
  },
  {
    id: 'airbus-acj319neo',
    name: 'Airbus ACJ319neo',
    manufacturer: 'Airbus Corporate Jets',
    category: 'VIP Airliner',
    mtowKg: 75500,
    mtowRange: '70,000+ kg',
    maxPassengers: 25,
    icao: 'A319',
    rangeNm: 6750,
    baseHandlingFeeUsd: { domestic: 3750, international: 5800 },
    landingParkingFeeUsdPerDay: { domestic: 830, international: 1600 },
    paxFeeUsdPerPax: 65,
  },
  {
    id: 'airbus-acj320neo',
    name: 'Airbus ACJ320neo',
    manufacturer: 'Airbus Corporate Jets',
    category: 'VIP Airliner',
    mtowKg: 79000,
    mtowRange: '70,000+ kg',
    maxPassengers: 25,
    icao: 'A320',
    rangeNm: 6000,
    baseHandlingFeeUsd: { domestic: 3850, international: 5950 },
    landingParkingFeeUsdPerDay: { domestic: 860, international: 1680 },
    paxFeeUsdPerPax: 65,
  },
  {
    id: 'embraer-lineage-1000e',
    name: 'Embraer Lineage 1000E',
    manufacturer: 'Embraer',
    category: 'VIP Airliner',
    mtowKg: 54500,
    mtowRange: '50,001 – 60,000 kg',
    maxPassengers: 19,
    icao: 'E190',
    rangeNm: 4600,
    baseHandlingFeeUsd: { domestic: 2850, international: 4400 },
    landingParkingFeeUsdPerDay: { domestic: 580, international: 1150 },
    paxFeeUsdPerPax: 55,
  },
  // ==================== ADDITIONAL BUSINESS AIRCRAFT ====================
  {
    id: 'gulfstream-g400',
    name: 'Gulfstream G400',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Ultra Long Range',
    mtowKg: 36000,
    mtowRange: '30,001 – 40,000 kg',
    maxPassengers: 12,
    icao: 'G400',
    rangeNm: 4200,
    baseHandlingFeeUsd: { domestic: 2150, international: 3400 },
    landingParkingFeeUsdPerDay: { domestic: 430, international: 850 },
    paxFeeUsdPerPax: 50,
  },
  {
    id: 'gulfstream-g300',
    name: 'Gulfstream G300',
    manufacturer: 'Gulfstream Aerospace',
    category: 'Heavy Jet',
    mtowKg: 31700,
    mtowRange: '30,001 – 40,000 kg',
    maxPassengers: 13,
    icao: 'G300',
    rangeNm: 3600,
    baseHandlingFeeUsd: { domestic: 1950, international: 3050 },
    landingParkingFeeUsdPerDay: { domestic: 380, international: 760 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'challenger-601-3a',
    name: 'Canadair Challenger 601-3A',
    manufacturer: 'Bombardier',
    category: 'Heavy Jet',
    mtowKg: 20457,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 12,
    icao: 'CL60',
    rangeNm: 3400,
    baseHandlingFeeUsd: { domestic: 1750, international: 2750 },
    landingParkingFeeUsdPerDay: { domestic: 295, international: 590 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'learjet-40xr',
    name: 'Learjet 40XR',
    manufacturer: 'Bombardier',
    category: 'Light Jet',
    mtowKg: 9230,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 7,
    icao: 'LJ45',
    rangeNm: 1735,
    baseHandlingFeeUsd: { domestic: 1120, international: 1780 },
    landingParkingFeeUsdPerDay: { domestic: 175, international: 350 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'learjet-70',
    name: 'Learjet 70',
    manufacturer: 'Bombardier',
    category: 'Light Jet',
    mtowKg: 9752,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 7,
    icao: 'LJ75',
    rangeNm: 2060,
    baseHandlingFeeUsd: { domestic: 1150, international: 1800 },
    landingParkingFeeUsdPerDay: { domestic: 180, international: 360 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'falcon-2000',
    name: 'Dassault Falcon 2000',
    manufacturer: 'Dassault Aviation',
    category: 'Heavy Jet',
    mtowKg: 18600,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 10,
    icao: 'F2TH',
    rangeNm: 3000,
    baseHandlingFeeUsd: { domestic: 1580, international: 2450 },
    landingParkingFeeUsdPerDay: { domestic: 265, international: 520 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'falcon-900b',
    name: 'Dassault Falcon 900B',
    manufacturer: 'Dassault Aviation',
    category: 'Heavy Jet',
    mtowKg: 20640,
    mtowRange: '20,001 – 30,000 kg',
    maxPassengers: 12,
    icao: 'F900',
    rangeNm: 3800,
    baseHandlingFeeUsd: { domestic: 1760, international: 2780 },
    landingParkingFeeUsdPerDay: { domestic: 300, international: 600 },
    paxFeeUsdPerPax: 45,
  },
  {
    id: 'falcon-50',
    name: 'Dassault Falcon 50',
    manufacturer: 'Dassault Aviation',
    category: 'Super Midsize',
    mtowKg: 17600,
    mtowRange: '15,001 – 20,000 kg',
    maxPassengers: 9,
    icao: 'FA50',
    rangeNm: 3100,
    baseHandlingFeeUsd: { domestic: 1500, international: 2350 },
    landingParkingFeeUsdPerDay: { domestic: 250, international: 500 },
    paxFeeUsdPerPax: 40,
  },
  {
    id: 'citation-vi',
    name: 'Cessna Citation VI',
    manufacturer: 'Textron Aviation',
    category: 'Midsize Jet',
    mtowKg: 10000,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 8,
    icao: 'C650',
    rangeNm: 2000,
    baseHandlingFeeUsd: { domestic: 1180, international: 1840 },
    landingParkingFeeUsdPerDay: { domestic: 185, international: 370 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'citation-iii',
    name: 'Cessna Citation III',
    manufacturer: 'Textron Aviation',
    category: 'Midsize Jet',
    mtowKg: 9980,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 8,
    icao: 'C650',
    rangeNm: 1950,
    baseHandlingFeeUsd: { domestic: 1160, international: 1820 },
    landingParkingFeeUsdPerDay: { domestic: 182, international: 364 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'citation-ultra',
    name: 'Cessna Citation Ultra',
    manufacturer: 'Textron Aviation',
    category: 'Light Jet',
    mtowKg: 7394,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 7,
    icao: 'C560',
    rangeNm: 1650,
    baseHandlingFeeUsd: { domestic: 1050, international: 1650 },
    landingParkingFeeUsdPerDay: { domestic: 160, international: 320 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'citation-encore-plus',
    name: 'Cessna Citation Encore+',
    manufacturer: 'Textron Aviation',
    category: 'Light Jet',
    mtowKg: 7543,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 8,
    icao: 'C560',
    rangeNm: 1780,
    baseHandlingFeeUsd: { domestic: 1060, international: 1680 },
    landingParkingFeeUsdPerDay: { domestic: 162, international: 324 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'hawker-800xp2',
    name: 'Hawker 800XPi',
    manufacturer: 'Hawker Beechcraft',
    category: 'Midsize Jet',
    mtowKg: 12700,
    mtowRange: '10,001 – 15,000 kg',
    maxPassengers: 8,
    icao: 'H25B',
    rangeNm: 2700,
    baseHandlingFeeUsd: { domestic: 1300, international: 2050 },
    landingParkingFeeUsdPerDay: { domestic: 210, international: 420 },
    paxFeeUsdPerPax: 35,
  },
  {
    id: 'hawker-400xp-exec',
    name: 'Beechjet 400A Executive',
    manufacturer: 'Hawker Beechcraft',
    category: 'Light Jet',
    mtowKg: 7394,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 7,
    icao: 'BE40',
    rangeNm: 1450,
    baseHandlingFeeUsd: { domestic: 1050, international: 1650 },
    landingParkingFeeUsdPerDay: { domestic: 160, international: 320 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'pilatus-pc12-47e',
    name: 'Pilatus PC-12/47E',
    manufacturer: 'Pilatus Aircraft',
    category: 'Turboprop',
    mtowKg: 4740,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 9,
    icao: 'PC12',
    rangeNm: 1740,
    baseHandlingFeeUsd: { domestic: 880, international: 1350 },
    landingParkingFeeUsdPerDay: { domestic: 125, international: 250 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'king-air-90',
    name: 'Beechcraft King Air C90GTx',
    manufacturer: 'Textron Aviation',
    category: 'Turboprop',
    mtowKg: 4756,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 6,
    icao: 'BE9L',
    rangeNm: 1150,
    baseHandlingFeeUsd: { domestic: 850, international: 1300 },
    landingParkingFeeUsdPerDay: { domestic: 120, international: 240 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'bell-525',
    name: 'Bell 525 Relentless',
    manufacturer: 'Bell Helicopter',
    category: 'Helicopter',
    mtowKg: 9298,
    mtowRange: '7,001 – 10,000 kg',
    maxPassengers: 16,
    icao: 'B525',
    rangeNm: 500,
    baseHandlingFeeUsd: { domestic: 1100, international: 1700 },
    landingParkingFeeUsdPerDay: { domestic: 170, international: 340 },
    paxFeeUsdPerPax: 30,
  },
  {
    id: 'leonardo-aw169',
    name: 'Leonardo AW169',
    manufacturer: 'Leonardo Helicopters',
    category: 'Helicopter',
    mtowKg: 4800,
    mtowRange: '0 – 5,000 kg',
    maxPassengers: 10,
    icao: 'A169',
    rangeNm: 440,
    baseHandlingFeeUsd: { domestic: 850, international: 1320 },
    landingParkingFeeUsdPerDay: { domestic: 120, international: 240 },
    paxFeeUsdPerPax: 25,
  },
  {
    id: 'boeing-bbj-max7',
    name: 'Boeing BBJ MAX 7',
    manufacturer: 'Boeing Corporate Jets',
    category: 'VIP Airliner',
    mtowKg: 80286,
    mtowRange: '70,000+ kg',
    maxPassengers: 30,
    icao: 'B737',
    rangeNm: 7000,
    baseHandlingFeeUsd: { domestic: 3900, international: 6000 },
    landingParkingFeeUsdPerDay: { domestic: 880, international: 1700 },
    paxFeeUsdPerPax: 65,
  },
];

export const USD_TO_NGN_RATE = 1550; // Current estimated rate

export function getAircraftById(id: string): FleetAircraft | undefined {
  return AIRCRAFT_DATASET.find((a) => a.id === id);
}

export function searchAircraft(query: string): FleetAircraft[] {
  if (!query || query.trim() === '') return AIRCRAFT_DATASET;
  const q = query.toLowerCase().trim();
  return AIRCRAFT_DATASET.filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      a.manufacturer.toLowerCase().includes(q) ||
      a.icao.toLowerCase().includes(q) ||
      a.category.toLowerCase().includes(q)
  );
}

export function calculateEstimatedQuote(input: QuoteCalculationInput): QuoteCalculationResult {
  const aircraft = input.customAircraft || getAircraftById(input.aircraftId) || AIRCRAFT_DATASET[0];
  const isIntl = input.operation === 'international';
  const isWeekend = input.movement === 'weekend';
  const isOvernight = input.stay === 'overnight';
  const nights = isOvernight ? Math.max(1, input.overnightNights || 1) : 0;
  const paxCount = Math.max(1, Math.min(input.passengers, aircraft.maxPassengers));

  // 1. Base Ramp & FBO Handling Fee
  const baseHandling = isIntl
    ? aircraft.baseHandlingFeeUsd.international
    : aircraft.baseHandlingFeeUsd.domestic;
  
  // Weekend surcharge (10% on handling for weekend operations)
  const weekendSurcharge = isWeekend ? Math.round(baseHandling * 0.1) : 0;

  // 2. Airport Landing & Navigation Estimate
  const landingFee = isIntl ? Math.round(aircraft.mtowKg * 0.022) : Math.round(aircraft.mtowKg * 0.012);

  // 3. Overnight Parking Fee
  const dailyParkingRate = isIntl
    ? aircraft.landingParkingFeeUsdPerDay.international
    : aircraft.landingParkingFeeUsdPerDay.domestic;
  const parkingTotal = isOvernight ? dailyParkingRate * nights : 0;

  // 4. Passenger Handling & Security Fee
  const paxHandlingTotal = paxCount * aircraft.paxFeeUsdPerPax;

  const breakdown: QuoteItemBreakdown[] = [
    {
      label: `FBO Ground Handling (${input.operation === 'domestic' ? 'Domestic' : 'International'})`,
      amountUsd: baseHandling,
      detail: `${aircraft.category} rate tier (${aircraft.mtowRange})`,
    },
  ];

  if (weekendSurcharge > 0) {
    breakdown.push({
      label: 'Weekend Operations Surcharge (10%)',
      amountUsd: weekendSurcharge,
      detail: 'Ramp staffing & priority coordination',
    });
  }

  breakdown.push({
    label: 'Airport Landing & Navigation (Est.)',
    amountUsd: landingFee,
    detail: `Calculated on ${aircraft.mtowKg.toLocaleString()} kg MTOW`,
  });

  if (parkingTotal > 0) {
    breakdown.push({
      label: `Overnight Hangar / Parking (${nights} ${nights === 1 ? 'night' : 'nights'})`,
      amountUsd: parkingTotal,
      detail: `$${dailyParkingRate}/night for ${input.location === 'lagos' ? 'Lagos MMIA' : 'Abuja DNAA'}`,
    });
  }

  breakdown.push({
    label: `Passenger VIP Facilitation (${paxCount} ${paxCount === 1 ? 'pax' : 'pax'})`,
    amountUsd: paxHandlingTotal,
    detail: `$${aircraft.paxFeeUsdPerPax}/passenger`,
  });

  // 5. Add-ons
  if (input.addOns?.vipLounge) {
    const loungeTotal = paxCount * 75;
    breakdown.push({
      label: 'EAN Executive VIP Terminal Pass',
      amountUsd: loungeTotal,
      detail: `$75/guest access including private suite & bar`,
    });
  }

  if (input.addOns?.catering) {
    const cateringEst = paxCount * 120;
    breakdown.push({
      label: 'Wings™ Executive In-Flight Catering (Est.)',
      amountUsd: cateringEst,
      detail: 'Freshly prepared 3-course gourmet flight meals',
    });
  }

  if (input.addOns?.gpuPower) {
    breakdown.push({
      label: 'GPU Ground Power Unit Support (2 hrs)',
      amountUsd: 250,
      detail: 'Aircraft power & cabin pre-cooling',
    });
  }

  if (input.addOns?.waterService) {
    breakdown.push({
      label: 'Potable Water & Lavatory Servicing',
      amountUsd: 180,
      detail: 'Full replenishment & sanitation',
    });
  }

  const totalUsd = breakdown.reduce((sum, item) => sum + item.amountUsd, 0);
  const totalNgn = totalUsd * USD_TO_NGN_RATE;

  return {
    aircraft,
    locationName: input.location === 'lagos' ? 'Murtala Muhammed Int\'l Airport, Lagos (MMIA)' : 'Nnamdi Azikiwe Int\'l Airport, Abuja (DNAA)',
    operationName: input.operation === 'domestic' ? 'Domestic Flight' : 'International Flight',
    movementName: input.movement === 'weekday' ? 'Weekday Schedule' : 'Weekend Schedule',
    stayName: isOvernight ? `${nights} Night${nights > 1 ? 's' : ''} Overnight` : 'Same-day Turnaround',
    passengers: paxCount,
    breakdown,
    totalUsd,
    totalNgn,
    fxRate: USD_TO_NGN_RATE,
  };
}
